apiVersion: batch/v1
kind: Job
metadata:
  name: training-job
  labels:
    app: mlflow
spec:
  template:
    spec:
      containers:
      - name: training-container
        image: training:v1
        command: ["python", "train.py"]
      restartPolicy: Never
