apiVersion: v1
kind: Pod 
metadata:
  name: app1
  labels:
    app: app1
spec:
  containers:
  - name: app1
    image: app1:v1
    env:
    - name: MLFLOW_SERVICE_PORT
      value: "5000"
    - name: MLFLOW_SERVICE_HOST
      value: "10.106.252.55"
    resources:
      requests:
        memory: "512Mi"
        cpu: "1000m"
      limits:
        memory: "1000Mi"
        cpu: "2000m"
    ports:
    - containerPort: 8000
---
apiVersion: v1 
kind: Service 
metadata:
  name: app1-service
spec:
  selector:
    app: app1
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
