apiVersion: v1
kind: Pod 
metadata:
  name: multicontainer
spec:
  containers:
  - name: mlflow
    image: ghcr.io/mlflow/mlflow:v2.20.1
    command:
      - mlflow
      - server
    env:
      - name: MLFLOW_BACKEND_STORE_URI
        value: sqlite:///mnt/mlflow.db
      - name: MLFLOW_HOST
        value: "0.0.0.0"
      - name: MLFLOW_PORT
        value: "5000"
    volumeMounts:
      - name: mlflow-backend-store
        mountPath: mnt/
    resources:
      requests:
        memory: "1024Mi"
        cpu: "1000m"
      limits:
        memory: "2048Mi"
        cpu: "5000m"
    ports:
    - containerPort: 5000
      protocol: TCP
  - name: app
    image: simpleexplist:v1
    env:
      - name: MLFLOW_TRACKING_URI
        value: http://localhost:5000
    resources:
      requests:
        cpu: 1000m
        memory: 512Mi
      limits:
        cpu: 2000m
        memory: 1024Mi
    ports:
    - containerPort: 8000
      protocol: TCP

  volumes:
  - name: mlflow-backend-store
    emptyDir: {}